language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script:
  - phpenv rehash
  - echo 'memory_limit = 2048M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update
  - composer validate
  - composer require --no-update silverstripe/recipe-core:4.5.x-dev
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
 - vendor/bin/phpunit --coverage-clover=coverage.xml ./tests

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.xml
